# Generated by Django 5.2.3 on 2025-06-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_remove_post_publicado_por_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='criado_em',
            new_name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
