# Generated by Django 5.2.3 on 2025-06-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoadocao',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoadocao',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='aguardando', max_length=20),
        ),
    ]
